spring.application.name=routepal

# ???????????? OpenRouteService
ors.api.key=???_?????????_API_KEY_???
ors.api.url=https://api.openrouteservice.org/v2/directions/
# ?? ??????????????????? "cycling-road" (???????? ?????????) ??? ?????????????
ors.profile=cycling-road