spring.application.name=routepal

ors.api.key=???_?????????_API_KEY_???
ors.api.url=https://api.openrouteservice.org/v2/directions/

# Routing profile "cycling-road"
ors.profile=cycling-road

# --- API Limits ---
# Directions V2 (2000 / 40)
ors.api.limit.directions.daily=2000
ors.api.limit.directions.min=40
# Export V2 (100 / 5)
ors.api.limit.export.daily=100
ors.api.limit.export.min=5